
name: 'dbt_test'
version: '1.0.0'
config-version: 2

profile: 'dbt_test'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_test:
    +database: my_feature_lake
    +materialized: view
    +contract:
      enforced: true
      alias_types: false
    datalake:
      +group: datalake
    intermediate:
      +group: intermediate
    features:
      +materialized: table
      +file_format: parquet
      +location_root: "/home/bala/repo/learndbt/feature_store/"
      +group: feature_store
  elementary:
    +schema: "elementary"
    +file_format: delta

# dispatch:
#   - macro_namespace: dbt
#     search_order: ['dbt_project_evaluator', 'dbt']